[tool.black]
line-length = 100

[tool.isort]
line_length = 100
profile = "black"

[tool.mypy]
exclude = 'docs/conf\.py$|build/*'
explicit_package_bases = true
ignore_missing_imports = true

[tool.pylint.messages_control]

max-line-length = 100
disable = [
  "cyclic-import",
  "duplicate-code",
  "invalid-name",
  "line-too-long",
  "logging-fstring-interpolation",
  "missing-function-docstring",
  "no-value-for-parameter",
  "raise-missing-from",
  "too-few-public-methods",
  "too-many-locals",
  "unspecified-encoding",
  "use-a-generator"
]
